/** Activity row `type` values, written inline with every mutation. */
export const ACTIVITY_TYPES = {
  BOARD_CREATED: 'board.created',
  BOARD_UPDATED: 'board.updated',
  BOARD_CLOSED: 'board.closed',
  BOARD_REOPENED: 'board.reopened',
  MEMBER_ADDED: 'board.member_added',
  MEMBER_REMOVED: 'board.member_removed',
  LIST_CREATED: 'list.created',
  LIST_UPDATED: 'list.updated',
  LIST_MOVED: 'list.moved',
  LIST_ARCHIVED: 'list.archived',
  CARD_CREATED: 'card.created',
  CARD_UPDATED: 'card.updated',
  CARD_MOVED: 'card.moved',
  CARD_ARCHIVED: 'card.archived',
  CARD_LABEL_ADDED: 'card.label_added',
  CARD_LABEL_REMOVED: 'card.label_removed',
  CARD_MEMBER_ADDED: 'card.member_added',
  CARD_MEMBER_REMOVED: 'card.member_removed',
  CHECKLIST_CREATED: 'checklist.created',
  CHECKLIST_UPDATED: 'checklist.updated',
  CHECKLIST_DELETED: 'checklist.deleted',
  CHECKLIST_ITEM_CREATED: 'checklist_item.created',
  CHECKLIST_ITEM_UPDATED: 'checklist_item.updated',
  CHECKLIST_ITEM_DELETED: 'checklist_item.deleted',
  COMMENT_CREATED: 'comment.created',
  COMMENT_UPDATED: 'comment.updated',
  COMMENT_DELETED: 'comment.deleted',
  ATTACHMENT_ADDED: 'attachment.added',
  ATTACHMENT_REMOVED: 'attachment.removed',
  ATTACHMENT_COVER_SET: 'attachment.cover_set',
} as const;

export type ActivityType = (typeof ACTIVITY_TYPES)[keyof typeof ACTIVITY_TYPES];
